spring.jpa.hibernate.ddl-auto=create-drop
pring.application.name=b2_pensionat_review
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://db01.home.arpa/pensionat_db
spring.datasource.url=jdbc:mysql://10.0.5.21/pensionat_db
spring.datasource.username=pensionat_user
spring.datasource.password=VjA2f2X@9v7Zeau$xH&ESe!#
server.port=8082
